UNFSocProgCompSys/Controllers/AdminController.cs
using Microsoft.AspNetCore.Identity;
using UNFSocProgCompSys.Models;
using UNFSocProgCompSys.Services;
using Microsoft.AspNetCore.Mvc;

namespace UNFSocProgCompSys.Controllers
{
    public class AdminController : Controller
    {
        private readonly IAdminServices _AdminService;
        public AdminController(IAdminServices adminServices)
        {
            _AdminService = adminServices;
        }

        [HttpGet]
        public async Task<IActionResult> UserList()
        {
            var users = await _AdminService.GetUsers();
         
            var model = new EditUserViewModel()
            {
                Users = users
            };
            return View(model);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var success = await _AdminService.DeleteUserById(id);
            if (success)
            {
                return RedirectToAction("UserList");
            }
            return View("UserList");
        }

        public async Task<IActionResult> EditUser(string id)
        {
            var user = new EditUserViewModel();
            var UserProfileVals = await _AdminService.GetUserByIdAsync(id);
            
            user.FirstName = UserProfileVals.FirstName;
            user.LastName = UserProfileVals.LastName;
            user.Email = UserProfileVals.Email;
            user.Gender = UserProfileVals.Gender;
            user.ClassesTaken = UserProfileVals.ClassesTaken;
            user.School = UserProfileVals.School;
            user.Username = UserProfileVals.UserName;
            user.ProgLang = UserProfileVals.ProgLang;

            return View(user);
        }
        
        [HttpPost]
        public async Task<IActionResult> EditUser(string id,EditUserViewModel userEdit)
        {

            var resultOfEdit = await _AdminService.EditUserByIdAsync(id,userEdit);

            if (resultOfEdit == false)
            {
                return BadRequest("Edit of user profile has failed!");
            }
            return RedirectToAction("UserList");
        }

    }
}

UNFSocProgCompSys/Controllers/CompetitionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using UNFSocProgCompSys.Data;
using UNFSocProgCompSys.Models;

namespace UNFSocProgCompSys.Controllers
{
    [Authorize]
    public class CompetitionController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CompetitionController(ApplicationDbContext db)
        {
            _db = db;
        }

        //Page to sign up for a competition from a list of competitions
        public IActionResult CompetitionSignUp()
        {
            IEnumerable<Competition> CompetitionList = _db.Competitions;
            return View(CompetitionList);
        }

        //Page to view actions relating to a competition
        public IActionResult CompetitionHome(Guid? CompetitionID)
        {
            if(CompetitionID == null)
            {
                return NotFound();
            }
            else
            {
                var CurrentCompetition = _db.Competitions.Find(CompetitionID);

                if (CurrentCompetition == null)
                {
                    return NotFound();
                }
                else
                {
                    return View(CurrentCompetition);
                }
            }
        }//End of Competition Home
    }    // End of class CompetitionController
}        // End of namespace UNFSocProgCompSys.Controllers

UNFSocProgCompSys/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using UNFSocProgCompSys.Models;
using UNFSocProgCompSys.Services;
using Microsoft.AspNetCore.Authorization;

namespace UNFSocProgCompSys.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IProfileServices _ProfileServices;
        public ProfileController(IProfileServices ProfileServices)
        {
            _ProfileServices = ProfileServices;
        }

        public async Task<IActionResult> ViewProfile()
        {
            var UserId = User?.Claims.FirstOrDefault()?.Value;
            var ProfileViewModel = new ProfileView();
            var UserProfileVals = await _ProfileServices.GetUserByIdAsync(UserId);
            
            ProfileViewModel.FirstName = UserProfileVals.FirstName;
            ProfileViewModel.LastName = UserProfileVals.LastName;
            ProfileViewModel.Email = UserProfileVals.Email;
            ProfileViewModel.Gender = UserProfileVals.Gender;
            ProfileViewModel.ClassesTaken = UserProfileVals.ClassesTaken;
            ProfileViewModel.School = UserProfileVals.School;
            ProfileViewModel.Username = UserProfileVals.UserName;
            ProfileViewModel.ProgLang = UserProfileVals.ProgLang;
            
            return View(ProfileViewModel);
        }

        public async Task<IActionResult>EditProfile()
        {
            string? UserName = User?.Identity?.Name;
            var ProfileViewModel= new ProfileView();
            var UserProfileVals = await _ProfileServices.GetUserByNameAsync(UserName);

            ProfileViewModel.FirstName = UserProfileVals.FirstName;
            ProfileViewModel.LastName = UserProfileVals.LastName;
            ProfileViewModel.Email = UserProfileVals.Email;
            ProfileViewModel.Gender = UserProfileVals.Gender;
            ProfileViewModel.ClassesTaken = UserProfileVals.ClassesTaken;
            ProfileViewModel.School = UserProfileVals.School;
            ProfileViewModel.Username = UserProfileVals.UserName;
            ProfileViewModel.ProgLang = UserProfileVals.ProgLang;

            return View(ProfileViewModel);
        }
        
        [HttpPost]
        public async Task<IActionResult> EditProfile(ProfileView ProfileValues)
        {
            //string UserName=User?.Identity?.Name;
            //var UserId = User?.Claims.FirstOrDefault(x => x.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier")?.Value;
            var UserId = User?.Claims.FirstOrDefault()?.Value;

            if(UserId == null)
            {
                return BadRequest("UserId could not be retrieved");
            }
            
            var resultOfEdit =  await _ProfileServices.EditUserByIdAsync(UserId,ProfileValues);
            
            if(resultOfEdit == false)
            {
                return BadRequest("Edit of user profile has failed!");
            }
            return RedirectToAction("ViewProfile");
        }

     }

  }
    

UNFSocProgCompSys/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using UNFSocProgCompSys.Data;
using UNFSocProgCompSys.Services;
using UNFSocProgCompSys.Models;
using System;
using Microsoft.AspNetCore.Authorization;

namespace UNFSocProgCompSys.Controllers
{
    [Authorize]
    public class TeamController : Controller
    {

        private readonly ITeamServices _teamService;

        public TeamController(ITeamServices teamService)
        {
            _teamService = teamService;
        }

        public async Task<IActionResult> Index()
        {
            //Get teams from the database
            //IEnumerable<Team> TeamList = _db.Teams;
            var teams = await _teamService.GetTeamsAsync();

            //Put Teams into a model
            var model = new TeamViewModel()
            {
                Teams = teams
            };
            //Render view using the model
            return View(model);
        }
        public IActionResult Create()
        {
            return View();
        }

        //Creating a new Team and adding it to the database

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTeam(TeamEntity newTeam)
        {
            //Validate the entered team info
            if (!ModelState.IsValid)
            {
                return BadRequest("Could not add team.");
                //RedirectToAction("Create");
            }

            var successful = await _teamService.AddTeamAsync(newTeam);
            if (!successful)
            {
                return BadRequest("Could not add team.");
            }

            return RedirectToAction("Index");
        }
    }
}

UNFSocProgCompSys/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UNFSocProgCompSys</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UNFSocProgCompSys.styles.css" asp-append-version="true" />
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3" style="background-color: #000066;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UNFSocProgCompSys</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                    <ul class="navbar-nav flex-grow-1">
                           <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="CompetitionAdmin" asp-action="CompetitionManagement">Events</a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" >Team</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="UserList"> 
                                Student</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top text-white text-muted fixed-bottom">
        <div class="text-center" style="background-color: #000066">
            &copy; 2022 - UNFSocProgCompSys
        </div>
        </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UNFSocProgCompSys/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UNFSocProgCompSys</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UNFSocProgCompSys.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3" style="background-color: #000066;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UNFSocProgCompSys</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    @if(User?.Identity?.IsAuthenticated != false)
                        {
                           <li class="nav-item">
                                <a class="nav-link" asp-controller="Profile" asp-action="ViewProfile">HI @User?.Identity?.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Competition" asp-action="CompetitionSignUp">Programming Competitions</a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Team" asp-action="Create">Create a team</a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Team" asp-action="Index">View Team List</a>
                            </li>
                       
                            <li class="nav-item">
                                <form id="logoutForm" method="post" class="form-inline" asp-controller="Account"
                                asp-action="LogOff">
                                    <button type="submit" class="btn nav-link">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>  
                                                    <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                     
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top text-white footer text-muted" style="background-color: #000066">
        <div class="container ">
            <div class="row text-center d-flex justify-content-center">
        <div class="col-md-2">
        <a class="text-light" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
        </div>
        <div class="col-md-2">
        <a class="text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        </div>
        </div>
        <div class="text-center" style="background-color: rgba(0, 0, 0, 0.2)">
            &copy; 2022 - UNFSocProgCompSys
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>