UNFSocProgCompSys/Controllers/CompetitionAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UNFSocProgCompSys.Data;
using UNFSocProgCompSys.Models;

namespace UNFSocProgCompSys.Controllers
{   
   
    public class CompetitionAdminController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CompetitionAdminController(ApplicationDbContext db)
        {
            _db = db;
        }

        //Page to view competition list and manage competitions (Admin)
        public IActionResult CompetitionManagement()
        {
            IEnumerable<Competition> CompetitionList = _db.Competitions;
            return View(CompetitionList);
        }

        //Page to create a new competition (Admin), this is a GET action
        public IActionResult CompetitionCreate()
        {
            return View();
        }

        //POST action for page to create a new competition (Admin)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CompetitionCreate(Competition NewCompetition)
        {
            if (ModelState.IsValid)
            {
                _db.Competitions.Add(NewCompetition);
                _db.SaveChanges();
                return RedirectToAction("CompetitionManagement");
            }
            else
            {
                return View(NewCompetition);
            }
        }

        //Page to edit an existing competition (Admin), this is a GET action
        public IActionResult CompetitionEdit(Guid? CompetitionID)
        {
            if (CompetitionID == null)
            {
                return NotFound();
            }
            else
            {
                var CurrentCompetition = _db.Competitions.Find(CompetitionID);

                if (CurrentCompetition == null)
                {
                    return NotFound();
                }
                else
                {
                    return View(CurrentCompetition);
                }
            }
        }

        //POST action for page to edit an existing competition (Admin)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CompetitionEdit(Competition ExistingCompetition)
        {
            if (ModelState.IsValid)
            {
                _db.Competitions.Update(ExistingCompetition);
                _db.SaveChanges();
                return RedirectToAction("CompetitionManagement");
            }
            else
            {
                return View(ExistingCompetition);
            }
        }

        //Page to remove an existing competition (Admin), this is a GET action
        public IActionResult CompetitionRemove(Guid? CompetitionID)
        {
            if (CompetitionID == null)
            {
                return NotFound();
            }
            else
            {
                var CurrentCompetition = _db.Competitions.Find(CompetitionID);

                if (CurrentCompetition == null)
                {
                    return NotFound();
                }
                else
                {
                    return View(CurrentCompetition);
                }
            }
        }

        //POST action for page to remove an existing competition (Admin)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CompetitionRemovePost(Guid? CompetitionID)
        {
            var ExistingCompetition = _db.Competitions.Find(CompetitionID);

            if (ExistingCompetition == null)
            {
                return NotFound();
            }
            else
            {
                _db.Competitions.Remove(ExistingCompetition);
                _db.SaveChanges();
                return RedirectToAction("CompetitionManagement");
            }
        }
    }     //End of class CompetitionAdminController
}         //End of namespace UNFSocProgCompSys.Controllers

UNFSocProgCompSys/Views/CompetitionAdmin/CompetitionCreate.cshtml
@model Competition
@{
    ViewBag.Title = "Competition Create";
    Layout = "_AdminLayout";
}
<div>
    <h1>Create Competition</h1>
</div>

<!--Form for creating a competition-->
<form method="post">
    <div>
        <label asp-for="CompetitionName">Name</label><br>
        <input asp-for="CompetitionName" type="text" size="30" autofocus><br>
        <span asp-validation-for="CompetitionName" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="CompetitionStartTime">Start time</label><br>
        <input asp-for="CompetitionStartTime" type="datetime-local"><br>
        <span asp-validation-for="CompetitionStartTime" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="CompetitionEndTime">End time</label><br>
        <input asp-for="CompetitionEndTime" type="datetime-local"><br>
        <span asp-validation-for="CompetitionEndTime" class="text-danger"></span>
    </div>
    <div> <!--FIXME, location is not nullable in the database, need to adjust it somehow-->
        <label asp-for="CompetitionLocation">Location if known</label><br>
        <input asp-for="CompetitionLocation" type="text" size="30">
    </div>
    <div>
        <label asp-for="CompetitionDescription">Description</label><br>
        <textarea asp-for="CompetitionDescription" rows="5" cols="100"></textarea>
    </div>
    <div>
        <label asp-for="CompetitionMaxTeamSize">Maximum team size</label><br>
        <input asp-for="CompetitionMaxTeamSize" type="number" min="1" step="1" max="99" value="3">
    </div><br>
    <div>
        <input type="submit" value="Submit" class="btn btn-primary">
        <a asp-controller="CompetitionAdmin" asp-action="CompetitionManagement" class="btn btn-secondary">Back</a>
    </div>
</form>

<!--FIXME, figure out how to run the partial script for client side validation-->

UNFSocProgCompSys/Views/CompetitionAdmin/CompetitionEdit.cshtml
@model Competition

@{
    ViewBag.Title = "Edit Competition";
    Layout = "_AdminLayout";
}

<div>
    <h1>Edit Competition</h1>
</div>

<!--Form for editing a competition-->
<form method="post">
    <div>
        <label asp-for="CompetitionName">Name</label><br>
        <input asp-for="CompetitionName" type="text" size="30" autofocus><br>
        <span asp-validation-for="CompetitionName" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="CompetitionStartTime">Start time</label><br>
        <input asp-for="CompetitionStartTime" type="datetime-local"><br>
        <span asp-validation-for="CompetitionStartTime" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="CompetitionEndTime">End time</label><br>
        <input asp-for="CompetitionEndTime" type="datetime-local"><br>
        <span asp-validation-for="CompetitionEndTime" class="text-danger"></span>
    </div>
    <div> <!--FIXME, location is not nullable in the database, need to adjust it somehow-->
        <label asp-for="CompetitionLocation">Location if known</label><br>
        <input asp-for="CompetitionLocation" type="text" size="30">
    </div>
    <div>
        <label asp-for="CompetitionDescription">Description</label><br>
        <textarea asp-for="CompetitionDescription" rows="5" cols="100"></textarea>
    </div>
    <div>
        <label asp-for="CompetitionMaxTeamSize">Maximum team size</label><br>
        <input asp-for="CompetitionMaxTeamSize" type="number" min="1" step="1" max="99" value="3">
    </div><br>
    <div>
        <input type="submit" value="Save changes" class="btn btn-primary">
        <a asp-controller="CompetitionAdmin" asp-action="CompetitionManagement" class="btn btn-secondary">Back</a>
    </div>
</form>

<!--FIXME, figure out how to run the partial script for client side validation-->

UNFSocProgCompSys/Views/CompetitionAdmin/CompetitionManagement.cshtml
@model IEnumerable<Competition>
@{
    ViewBag.Title = "Competition List";
    Layout = "_AdminLayout";
}

<div>
    <!--FIXME search-->
    <a class="btn btn-secondary float-end">Search</a>
    <h1>Current Competitions</h1>
</div>
<div>
    <table class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Competition</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var competition in Model)
            {
                <tr>
                    <td>
                        <h3>@competition.CompetitionName</h3>

                        <div class="float-end">
                            <a asp-controller="CompetitionAdmin" asp-action="CompetitionEdit" 
                                asp-route-CompetitionID=@competition.CompetitionID class="btn btn-success">Edit</a>
                            <a asp-controller="CompetitionAdmin" asp-action="CompetitionRemove" 
                                asp-route-CompetitionID=@competition.CompetitionID class="btn btn-danger">Remove</a>
                        </div>
                        @competition.CompetitionDescription
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <!--FIXME Download CSV-->
    <a class="btn btn-secondary float-end">Download CSV</a>
    <a asp-controller="CompetitionAdmin" asp-action="CompetitionCreate" class="btn btn-primary">Create</a>
</div>

UNFSocProgCompSys/Views/CompetitionAdmin/CompetitionRemove.cshtml
@model Competition
@{
    ViewBag.Title = "Competition Remove";
    Layout = "_AdminLayout";
}

<div>
    <h1>Remove Competition</h1>
</div>

<!--Form for removing a competition-->
<form method="post" asp-action="CompetitionRemovePost">
    <input asp-for="CompetitionID" hidden></input>
    <div>
        <label asp-for="CompetitionName">Name</label><br>
        <input asp-for="CompetitionName" type="text" size="30" disabled>
    </div>
    <div>
        <label asp-for="CompetitionStartTime">Start time</label><br>
        <input asp-for="CompetitionStartTime" type="datetime-local" disabled>
    </div>
    <div>
        <label asp-for="CompetitionEndTime">End time</label><br>
        <input asp-for="CompetitionEndTime" type="datetime-local" disabled>
    </div>
    <div>
        <label asp-for="CompetitionLocation">Location if known</label><br>
        <input asp-for="CompetitionLocation" type="text" size="30" disabled>
    </div>
    <div>
        <label asp-for="CompetitionDescription">Description</label><br>
        <textarea asp-for="CompetitionDescription" rows="5" cols="100" disabled></textarea>
    </div>
    <div>
        <label asp-for="CompetitionMaxTeamSize">Maximum team size</label><br>
        <input asp-for="CompetitionMaxTeamSize" type="number" min="1" step="1" max="99" value="3" disabled>
    </div><br>
    <div>
        <input type="submit" value="Remove" class="btn btn-danger">
        <a asp-controller="CompetitionAdmin" asp-action="CompetitionManagement" class="btn btn-secondary">Back</a>
    </div>
</form>